sudo: required
services:
  - docker
before_install:
  - docker build -t kosmach/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run kosmach/react-test npm test -- --coverage
after_success:
  - docker build -t kosmach/multi-client ./client
  - docker build -t kosmach/multi-nginx ./nginx
  - docker build -t kosmach/multi-server ./server
  - docker build -t kosmach/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kosmach/multi-client
  - docker push kosmach/multi-nginx
  - docker push kosmach/multi-server
  - docker push kosmach/multi-worker