sudo: required
services:
  - docker
before_install:
  - docker build -t kosmach/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run kosmach/react-test npm test -- --coverage
after_success:
  - docker build -t kosmach/multi-client ./client
  - docker build -t kosmach/multi-nginx ./nginx
  - docker build -t kosmach/multi-server ./server
  - docker build -t kosmach/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kosmach/multi-client
  - docker push kosmach/multi-nginx
  - docker push kosmach/multi-server
  - docker push kosmach/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-886213076879
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
